2014/05/15 01:24:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php:381
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/generators/model/ModelCode.php(57): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#15 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/certificados/index.php/gii/model
HTTP_REFERER=http://localhost/certificados/index.php/gii/default/index
---
2014/05/15 01:24:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'certificado'' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php:381
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/generators/model/ModelCode.php(57): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#15 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/certificados/index.php/gii/model
HTTP_REFERER=http://localhost/certificados/index.php/gii/default/index
---
2014/05/15 01:50:28 [error] [exception.CException] exception 'CException' with message 'El alias "application.components.WebUser" es inválido. Asegúrese de que apunta a un archivo PHP y el archivo tiene permisos de lectura.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php:316
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php(196): YiiBase::import('application.com...', true)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(386): YiiBase::createComponent(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('user')
#3 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/layouts/main.php(35): CModule->__get('user')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/Applications/X...', Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(206): COutputProcessor->run()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#11 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/layouts/column1.php(6): CBaseController->endContent()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(784): CBaseController->renderFile('/Applications/X...', Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/SiteController.php(32): CController->render('index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/certificados/index.php/site/login
HTTP_REFERER=http://localhost/certificados/index.php
---
2014/05/15 01:59:36 [error] [exception.CException] exception 'CException' with message 'SiteController no ha podido encontrar la vista "resetpass" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:878
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('resetpass', Array, true)
#1 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/SiteController.php(130): CController->render('resetpass', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionResetPass()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('resetpass')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/resetpass')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#9 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/certificados/index.php?r=site/resetpass
HTTP_REFERER=http://localhost/certificados/index.php?r=site/login
---
2014/05/17 00:54:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "certi_anoni" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('certi_anoni')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('certi_anoni')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/certi_anon...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php?r=site/certi_anoni
---
2014/05/17 00:54:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "gii" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('gii')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('gii')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/gii')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php?r=site/gii
---
2014/05/17 00:54:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 00:55:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 00:55:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 00:55:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 00:55:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 00:55:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 00:59:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/
---
2014/05/17 01:02:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:02:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:02:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:02:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:02:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:02:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:02:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:02:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:03:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "..." solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('...')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/.../images...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/.../images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:03:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:03:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:03:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:03:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:03:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:03:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/footer.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('images/footer.j...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:04:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:04:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:05:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:05:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:05:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:05:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:05:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:05:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:11:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('proveedor/image...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/proveedor/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/proveedor/create
---
2014/05/17 01:11:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('proveedor/image...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/proveedor/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/proveedor/create
---
2014/05/17 01:32:44 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'certificados.tipoarticulo' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `tipoarticulo`.
in /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php (13)
2014/05/17 01:44:18 [error] [exception.CDbException] exception 'CDbException' with message 'Tabla "usuario" no contiene la columna "usuario".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbCommandBuilder.php:591
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1464): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/components/UserIdentity.php(49): CActiveRecord->findByAttributes(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/models/LoginForm.php(54): UserIdentity->authenticate()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/SiteController.php(94): CModel->validate()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('login')
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#14 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/certificados/index.php/site/login
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:45:25 [error] [exception.CDbException] exception 'CDbException' with message 'Tabla "usuario" no contiene la columna "usuario".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbCommandBuilder.php:591
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1464): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/components/UserIdentity.php(49): CActiveRecord->findByAttributes(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/models/LoginForm.php(54): UserIdentity->authenticate()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/SiteController.php(94): CModel->validate()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('login')
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#14 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/certificados/index.php/site/login
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 01:53:43 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'certificado.certificado' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `certificado`.
in /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php (13)
2014/05/17 01:53:43 [error] [exception.CDbException] exception 'CDbException' with message 'La tabla "certificado" definida en la clase active record "Certificado" no se ha podido encontrar en la base de datos.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2310
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(Certificado))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/generators/crud/CrudCode.php(66): CActiveRecord::model('Certificado')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CInlineValidator.php(42): CrudCode->validateModel('model', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(CrudCode), 'model')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModel.php(159): CValidator->validate(Object(CrudCode), NULL)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(159): CModel->validate()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#14 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/certificados/index.php/gii/crud
HTTP_REFERER=http://localhost/certificados/index.php/gii/crud
---
2014/05/17 02:08:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('images')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('images')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/images/foo...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/certificados/index.php/site/images/footer.jpg
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 02:10:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "sit"' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sit')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/certificados/index.php/sit
---
2014/05/17 02:25:42 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."pass" no se encuentra definida.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/components/UserIdentity.php(52): CComponent->__get('pass')
#1 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/models/LoginForm.php(54): UserIdentity->authenticate()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/SiteController.php(94): CModel->validate()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#13 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/certificados/index.php/site/login
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 02:30:35 [error] [exception.CException] exception 'CException' with message 'Usuario y sus behaviors no tienen un método o closure llamado "validatePassword".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:265
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(225): CComponent->__call('validatePasswor...', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/components/UserIdentity.php(52): CActiveRecord->__call('validatePasswor...', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/components/UserIdentity.php(52): Usuario->validatePassword('admin')
#3 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/models/LoginForm.php(54): UserIdentity->authenticate()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/SiteController.php(94): CModel->validate()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('login')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#15 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/certificados/index.php/site/login
HTTP_REFERER=http://localhost/certificados/index.php/site/login
---
2014/05/17 04:26:40 [error] [php] include(Perfil.php): failed to open stream: No such file or directory (/Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php:421)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/usuario/_form.php(70): spl_autoload_call()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): UsuarioController->renderInternal()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): UsuarioController->renderFile()
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/usuario/create.php(18): UsuarioController->renderPartial()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): UsuarioController->renderInternal()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): UsuarioController->renderFile()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): UsuarioController->renderPartial()
#9 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/UsuarioController.php(79): UsuarioController->render()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): UsuarioController->actionCreate()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): UsuarioController->runAction()
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CAccessControlFilter->filter()
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): UsuarioController->filterAccessControl()
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): UsuarioController->runActionWithFilters()
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): UsuarioController->run()
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#22 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CWebApplication->run()
REQUEST_URI=/certificados/index.php/usuario/create
in /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/usuario/_form.php (70)
in /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/usuario/create.php (18)
in /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/UsuarioController.php (79)
2014/05/17 04:48:59 [error] [exception.CException] exception 'CException' with message 'ArticuloController tiene una llamada extra a endWidget() en su vista.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php:210
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/articulo/_form.php(37): CBaseController->endWidget()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#4 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/articulo/create.php(18): CController->renderPartial('_form', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('create', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/ArticuloController.php(79): CController->render('create', Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): ArticuloController->actionCreate()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('create')
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('articulo/create')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#22 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/certificados/index.php/articulo/create
HTTP_REFERER=http://localhost/certificados/index.php/proveedor/create
---
2014/05/17 04:57:22 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'PRIMARY'. La sentencia SQL ejecutada fue: INSERT INTO `articulo` (`nombre_articulo`) VALUES (:yp0).
in /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/ArticuloController.php (73)
in /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php (13)
2014/05/17 04:57:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `articulo` (`nombre_articulo`) VALUES (:yp0)' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:357
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1023): CDbCommand->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(795): CActiveRecord->insert(NULL)
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/ArticuloController.php(73): CActiveRecord->save()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): ArticuloController->actionCreate()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('create')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('articulo/create')
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#15 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/certificados/index.php/articulo/create
HTTP_REFERER=http://localhost/certificados/index.php/articulo/create
---
2014/05/17 04:58:01 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'PRIMARY'. La sentencia SQL ejecutada fue: INSERT INTO `articulo` (`nombre_articulo`) VALUES (:yp0).
in /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/ArticuloController.php (73)
in /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php (13)
2014/05/17 04:58:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `articulo` (`nombre_articulo`) VALUES (:yp0)' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:357
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1023): CDbCommand->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(795): CActiveRecord->insert(NULL)
#2 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/ArticuloController.php(73): CActiveRecord->save()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): ArticuloController->actionCreate()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('create')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('articulo/create')
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#15 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/certificados/index.php/articulo/create
HTTP_REFERER=http://localhost/certificados/index.php/articulo/create
---
